name: Deploy Backend to Google Cloud Run

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  setup_build:
    name: Setup and Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2



    - name: Build and Deploy to Cloud Run
      run: |
        gcloud builds submit --tag gcr.io/PROJECT_ID/MY_SERVICE
        gcloud run deploy MY_SERVICE --image gcr.io/PROJECT_ID/MY_SERVICE --platform managed
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

